### ISSUE TITLE
Remove version check

### ISSUE THREAD

**Issue by andychisholm** [redbrick-ai/redbrick-sdk#163]
The current version check logic has a number of drawbacks. I.e.
- It creates (otherwise unnecessary) directories and config files
- It runs http requests to check latest pypi version
- It produces unnecessary warnings (e.g. if the client is compatible you shouldn't need to upgrade)

All of this happens on import of the redbrick module and so there is no way to opt out of it. This unnecessarily slows down any production code which imports redbrick, inadvertently or otherwise, even if the client isn't being used. (and has side effect causing e.g. https://github.com/redbrick-ai/redbrick-sdk/issues/148)

This behavior might make sense for ex-production use cases of the redbrick SDK but I think it is otherwise a bit unorthodox.

Suggestion would be, either remove the version check, or delay it to when a client is created and allow opt-out.

**Comment by pritamrungta** [comment]
Hi @andychisholm 
We've released a new version [v2.13.4](https://pypi.org/project/redbrick-sdk/2.13.4/) addressing this issue.
Now importing redbrick won't automatically do the version checking.
Could you give it a try and let us know if it works.

**Comment by andychisholm** [comment]
Thanks @pritamrungta , looking good 🚀 .
