### ISSUE TITLE
Type information is missing from packaged distribution

### ISSUE THREAD

**Issue by anaoum** [redbrick-ai/redbrick-sdk#164]
The redbrick-sdk contains type annotations which can be very useful for downstream projects.

Unfortunately, without explicitly marking that the package contains type annotations, downstream packages cannot make use of these hints. As a result, you need to ignore imports of redbrick when using mypy:
```python
import redbrick  # type: ignore[import]
```

The fix for this is rather simple and involves including an empty file named "py.typed" in the redbrick module in your distributed package. See [PEP-561](https://peps.python.org/pep-0561/) for more information.

**Comment by pritamrungta** [comment]
Thanks @anaoum
That's a great suggestion. Marking it for the next release

**Comment by pritamrungta** [comment]
Hi @anaoum 

We've released a new version [v2.13.4](https://pypi.org/project/redbrick-sdk/2.13.4/) addressing this issue.
Could you give it a try and let us know if it works.

Thanks!

**Comment by anaoum** [comment]
It is working, thank you.
