### ISSUE TITLE
It is not possible to set/update a label validation script via the SDK

### ISSUE THREAD

**Issue by anaoum** [redbrick-ai/redbrick-sdk#167]
We would like to be able to set and update a label validation script for each project using the SDK.

In general, we would like as much of the project creation process as possible to be done via the SDK, avoiding the manual task of copying in the same settings for multiple projects. This will ensure that we can create reproducible labelling environments.

**Comment by pritamrungta** [comment]
That is a great suggestion @anaoum 
Please allow us some time, while we scope this out internally.

**Comment by anaoum** [comment]
@pritamrungta just following up on this.

**Comment by pritamrungta** [comment]
Hi @anaoum 
This has been done in the latest version (v2.13.14)
Docs here: https://redbrick-sdk.readthedocs.io/en/stable/sdk.html#redbrick.settings.Settings.label_validation
Thanks!
