### ISSUE TITLE
Create project fails (sometimes) when you have more than 50 taxonomies

### ISSUE THREAD

**Issue by andychisholm** [redbrick-ai/redbrick-sdk#168]
When creating a project we observe a "Taxonomy {name} does not exist" exception triggered by:
https://github.com/redbrick-ai/redbrick-sdk/blob/master/redbrick/organization/__init__.py#L179

The underlying issue seems to be that this call `self.context.project.get_taxonomies(self._org_id)` returns at most 50 taxonomies:
https://github.com/redbrick-ai/redbrick-sdk/blob/master/redbrick/organization/__init__.py#L40

This means if you're lucky enough to have your taxonomy return within that limit, you can create a project, otherwise it will incorrectly blow up. We have more than 50 taxonomies configured, so have started observing this.

**Comment by pritamrungta** [comment]
Hi @andychisholm 

Thank you for bringing this to our notice and for the detailed breakdown.
We've pushed a fix in the latest v2.13.12
Could you please confirm if that resolves the issue on your end

Thanks!
