### ISSUE TITLE
Avoid modifying global behaviours

### ISSUE THREAD

**Issue by andychisholm** [redbrick-ai/redbrick-sdk#171]
Hey all, just raising a couple of issues that I feel could really improve the library for use in production systems.

When the package is imported it automatically modifies a number of global behaviours, which a package should generally not do on behalf of a consuming application. E.g. [installing](https://github.com/redbrick-ai/redbrick-sdk/blob/27f8014191b77c88bf71eded9b763aa221ada6d7/redbrick/utils/logging.py#L11) `pretty` and `traceback` from rich to take over global logging/exception behaviour. If users want this in their production code, I think they should opt-into it rather than have a 3rd party package enforce it.

A similar but less critical issue is  `nest_asyncio`. This is less of a problem for us, although the [logging](https://github.com/redbrick-ai/redbrick-sdk/blob/27f8014191b77c88bf71eded9b763aa221ada6d7/redbrick/__init__.py#L50) in notebooks is a bit of an eyesore. I understand automating this is a bit quality of life win for notebook peoples, so I would suggest as an alternative [more specifically checking](https://stackoverflow.com/a/39662359) that you're in a jupyter interpreter and then not logging about it, or atleast not at the `.info` level.

**Comment by pritamrungta** [comment]
Hi @andychisholm

Thanks for your valuable feedback. We've incorporated the suggestions in the latest release ([v2.13.18](https://github.com/redbrick-ai/redbrick-sdk/releases/tag/v2.13.18)) :
- removed global install of poetry and traceback
- changed notebook logging level to warning.
