### ISSUE TITLE
feature request: Return sibling_tasks in Project object

### ISSUE THREAD

**Issue by daniellohrey-hai** [redbrick-ai/redbrick-sdk#179]
We'd like to check the currently configured sibling tasks in the returned Project when calling get_project (or create_project when exists_okay is true) since it is part of the project config.

Thanks

**Comment by pritamrungta** [comment]
Added in this commit: https://github.com/redbrick-ai/redbrick-sdk/commit/4bc84bd2f8148525fdbb65a802de0c1600ebab6a

This will be available in project's `settings` module in the upcoming release.
> Get: `count = project.settings.task_duplication`
> Set: `project.settings.task_duplication = count`

**Comment by pritamrungta** [comment]
Released in [v2.18.0](https://github.com/redbrick-ai/redbrick-sdk/releases/v2.18.0)
