### ISSUE TITLE
Incorrect segmentation masks uploaded when multiple series and overlaps are present

### ISSUE THREAD

**Issue by anaoum** [redbrick-ai/redbrick-sdk#197]
In [process_segmentation_upload](https://github.com/redbrick-ai/redbrick-sdk/blob/49f04022e9a3f4389448f8857740dd224fa45442/redbrick/utils/upload.py#L237), after each call to `process_nifti_upload`, we update the groupids of each label with those in the returned `group_map` from `process_nifti_upload`. However, we do not filter to only update the groupids for the labels in the _current_ series (`volumeindex`).

This can be problematic if there are multiple series. For example, consider a situation where:
- a task contains two series,
- the first series has three instances (`1`, `2` and `3`), and produces a single overlap group (`4` for instances `1` and `2`), and
- the second series has four instances (`1`, `2`, `3`, and `4`) and produces no overlap groups.

After the first call to `process_nifti_upload`, we set the groupids on instances `1` and `2` for labels on _all_ series to be group `4`.
After the second call to `process_nifti_upload`, we make no changes to the groupids.

The result is that instances `1` and `2` in _all_ series think that they should be including overlap group `4` as part of their segmentation mask, when only instances `1` and `2` from the _first_ series should. Thankfully, in the UI, we get an error that "Instance 4 has already been used" (because the UI identifies that instances `1` and `2` in series two use overlap group `4`, despite that series having an instance `4`)

Another problematic scenario that **does not manifest as an error in the UI**:
- a task contains two series,
- the first series has three instances (`1`, `2` and `3`), and produces a single overlap group (`4` for instances `1` and `2`), and
- the second series has three instances (`1`, `2` and `3`) and produces a single overlap group (`4` for instances `2` and `3`).

After the first call to `process_nifti_upload`, we set the groupids on instances `1` and `2` for labels on _all_ series to be group `4`.
After the second call to `process_nifti_upload`, we set the groupids on instances `2` and `3` for labels on _all_ series to be group `4`.

The result is that all instances (`1`, `2`, and `3`) in all series think they should be including overlap group `4` as part of their segmentation mask, when only instances `1` and `2` from the first series, and instances `2` and `3` for the second series, should be using group `4`. 

There are many more scenarios that are problematic when sharing the group map across all series, these are just two that I have tested/reproduced.

Note that this bug has been present even before the [recent improvements to process_nifti_upload](https://github.com/redbrick-ai/redbrick-sdk/releases/tag/v2.19.5).

**Comment by pritamrungta** [comment]
Thanks for the detailed info and the proposed solution.
We've modified it such that the labels are filtered per series to begin with, in order to avoid any related issues in the future.

Published in https://github.com/redbrick-ai/redbrick-sdk/releases/tag/v2.19.8
