### ISSUE TITLE
Issue uploading tasks with version 2.20.0

### ISSUE THREAD

**Issue by zndr27** [redbrick-ai/redbrick-sdk#207]
With version 2.20.0 of the redbrick SDK I'm getting the following error when trying to upload tasks to redbrick:

[...] WARNING  Failed to process segmentations: `Invalid label files` for ...

However, when I went back to version 2.19.8 it's working again.

**Comment by pritamrungta** [comment]
Hello @zndr27 

Since we might need to share sensitive content, it'll be better that we move to a private platform.
To begin with, could you please mail to support@redbrickai.com with the command/script that you're using for upload along with the terminal logs
