### ISSUE TITLE
Deprecation, update messages to user. 

### ISSUE THREAD

**Issue by shivam124081** [redbrick-ai/redbrick-sdk#30]
We should have some way of sending "deprecation" or "please upgrade to new version" messages to a user who is running an older version of the sdk. 

Possibly on `init` we can have an api call that checks the version and relays any messages to the user from the backed.

**Comment by dereklukacs** [comment]
https://stackoverflow.com/questions/58648739/how-to-check-if-python-package-is-latest-version-programmatically

^ might be helpful
