### ISSUE TITLE
Create datapoint was working, then stopped

### ISSUE THREAD

**Issue by shivam124081** [redbrick-ai/redbrick-sdk#33]
The create datapoint was working, but then when I ctrl+c the script and restarted it, it stopeed working and prints the following error: 

```
'CreateDatapoint' object has no attribute 'dset_assoc'
[ERROR]:  Could not create datapoint. Make sure your datapoint name is not repeated.
```

**Comment by shivam124081** [comment]
## Update

### Steps to reproduce
- Create datapoint with labels for a few images - everything works properly. 
- Recreate datapoints with the same labels and datapoint name, you will get the error above. 
- If you delete the dataset + labelset and re-run, you will still get the same error.

**Comment by dereklukacs** [comment]
This is an error caused by repeated names

**Comment by dereklukacs** [comment]
Issue moved, not a problem with SDK
