### ISSUE TITLE
download data, don't download data that is already downloaded (from prior exports)

### ISSUE THREAD

**Issue by dereklukacs** [redbrick-ai/redbrick-sdk#36]
Scenario:

1. I download all 50 images and labels in my labelset
2. I label 50 more images
3. I download the labelset again with all 100 images. But only download the new 50 and add to the existing 50.

**Comment by GioRdrz** [comment]
Possible incompatibility with feature use_name of Exporter class.
If use_name is True, then a collision check is performed until downloaded image has an unique filename.

Will implement only when use_name is False for now.

**Comment by dereklukacs** [comment]
This is a good compromise.
