### ISSUE TITLE
Cannot cancel upload with ctrl-c

### ISSUE THREAD

**Issue by dereklukacs** [redbrick-ai/redbrick-sdk#38]
Ctrl-c should stop the process.

The exception seems to be caught?

This what happens when I press ctrl-c:
![image](https://user-images.githubusercontent.com/34690251/112507817-60ca0e00-8d65-11eb-9268-236fb0189d48.png)

**Comment by GioRdrz** [comment]
Datapoint creation can be canceled with KeyboardInterrupt on version 0.3.9 of the SDK.
