### ISSUE TITLE
Requirements-dev.txt missing modules

### ISSUE THREAD

**Issue by shivam124081** [redbrick-ai/redbrick-sdk#6]
I get the following errors when I pip install requirements-dev.txt. I'm using python 3.7.0. 

`ModuleNotFoundError: No module named 'requests'`

<img width="1166" alt="Screen Shot 2020-12-07 at 11 54 46 AM" src="https://user-images.githubusercontent.com/39279017/101316832-4554f900-3883-11eb-95ce-fdebc773a0f7.png">

**Comment by sagarrakshe** [comment]
@shivam124081 What is the python version you are using?

**Comment by shivam124081** [comment]
I was using python `3.7.0`, I can try again and make sure that's what it was
